baseurl = "http://cirpo.org"
languageCode = "en-us"
title = "cirpo's blog pota"
paginate = 10
disqusShortname = "cirpo"


[author]
    name = "cirpo"
    twitter = "http://twitter.com/cirpo"
    url = "http://github.com/cirpo"

[params]
  twitterName = "cirpo"
  githubName = "cirpo"
  twitter = "cirpo"
